version: '3'
services:
    app:
      container_name: backend-serv
      restart: always
      build: ./BackendProj
      ports:
        - "3000:3000"
      volumes:
        - ./BackendProj:/usr/src/app
        - /usr/src/app/node_modules
      links:
        - db
      depends_on: 
        - "db"
      environment:
        WAIT_HOSTS: mongo:27017
    db:
      container_name: mongo
      image: mongo
    
