version: '3.7'
services:
  backend-serv:
    build: .
    ports:
      - "3000:3000"
    depends_on: 
        - mongodb
    links: 
        - mongodb
  mongodb:
    image: "mongo:latest"
    command: mongod --bind_ip_all
    ports:
        - "27017:27017"
    environment: 
        MONGO_INITDB_DATABASE: "catratmat"