version: '3'
services:
    app:
      container_name: backend-serv
      restart: always
      build: ./
      ports:
        - "3000:3000"
      volumes:
        - .:/app
      links:
        - db
      depends_on: 
        - "db"
    db:
      container_name: mongo
      image: mongo
      ports:
        - "27017:27017"
