version: '3.7'
services:
  backend-serv:
    container_name: backend-serv
    build: ./
    ports:
      - "3000:3000"
    depends_on: 
        - mongo
    links: 
        - "mongo"

  mongo:
    container_name: mongo
    image: "mongo:latest"
    command: mongod --bind_ip_all
    ports:
        - "27017:27017"
    environment: 
        MONGO_INITDB_DATABASE: "catratmat"

