version: '3'
services:
  backend-serv:
    build: .
    ports:
      - "3000:3000"
    depends_on: 
        - "mongo"
  mongo:
    image: "mongo:latest"
    command: mongod --bind_ip_all
    ports:
        - "27017:27017"